INSERT INTO STUDENT VALUES (1, 'Student 1', 1, 2, 3);
INSERT INTO STUDENT VALUES (2, 'Student 2', 2, 3, 4);
INSERT INTO STUDENT VALUES (3, 'Student 3', 3, 4 ,5);
INSERT INTO STUDENT VALUES (4, 'Student 4', 4, 5, 6);
INSERT INTO STUDENT VALUES (5, 'Student 5', 5, 6, 7);
